// Generated by convert_excel.py
// Contains data aggregated from .xlsx files

const allQuizData = {
  "pathology": {
    "Cell Injury and Inflammation": [
      {
        "question": "A 50-year-old female presents with cervical lymphadenopathy. A biopsy has revealed granulomatous necrotizing inflammation. Which of the following options is correct?",
        "options": [
          "Metastatic calcification with normal serum calcium level",
          "Dystrophic calcification with normal serum calcium level",
          "Metastatic calcification with raised serum calcium levels",
          "Dystrophic calcification with raised serum calcium level"
        ],
        "answer": "Dystrophic calcification with normal serum calcium level"
      },
      {
        "question": "Comment on the histopathology slide?",
        "options": [
          "Langhans cell",
          "Stellate cell",
          "Not provided",
          "Not provided"
        ],
        "answer": "Langhans cell"
      },
      {
        "question": "Which of the following are decreased in acute inflammation?",
        "options": [
          "NADPH oxidase",
          "Catalase",
          "Hepcidin",
          "Ferritin"
        ],
        "answer": "Hepcidin"
      },
      {
        "question": "Enzyme for respiratory burst in phagocytosis is?",
        "options": [
          "Myeloperoxidase",
          "NADPH oxidase",
          "Catalase",
          "Defensin"
        ],
        "answer": "Myeloperoxidase"
      },
      {
        "question": "A chronic alcoholic patient presents with multiple episodes of abdominal pain radiating to the back. Work up shows increased serum amylase levels. Which type of necrosis is likely to be present in this case?",
        "options": [
          "Fat necrosis",
          "Liquefactive necrosis",
          "Coagulative necrosis",
          "Dystrophic necrosis"
        ],
        "answer": "Fat necrosis"
      },
      {
        "question": "Apoptotic bodies contain:",
        "options": [
          "Organelle + Cytoplasm + Nucleus",
          "Cytoplasm",
          "Organelle",
          "Nucleus"
        ],
        "answer": "Organelle + Cytoplasm + Nucleus"
      },
      {
        "question": "Most radio-resistant phase of cell cycle?",
        "options": [
          "S",
          "M",
          "G1",
          "G2"
        ],
        "answer": "M"
      },
      {
        "question": "Sequence of wound healing?",
        "options": [
          "Hemostasis, inflammation, proliferation, remodeling",
          "Hemostasis, proliferation, remodeling, inflammation",
          "Inflammation, hemostasis, proliferation, remodeling",
          "Inflammation, proliferation, hemostasis, remodeling"
        ],
        "answer": "Hemostasis, inflammation, proliferation, remodeling"
      },
      {
        "question": "Netosis includes all except:",
        "options": [
          "Sepsis",
          "SARS-COV2",
          "Systemic lupus erythematosus",
          "G2"
        ],
        "answer": "G2"
      },
      {
        "question": "A 7-year-old boy presents with a history of recurrent bacterial and fungal infections, particularly involving the skin and respiratory tract. Parents report that he has had multiple abscesses and lymphadenitis since birth. Dihydrorhodamine test shows abnormal test results. What is the diagnosis based on these findings?",
        "options": [
          "Leukocyte adhesion deficiency",
          "Chronic granulomatous disease",
          "Severe combined immunodeficiency (SCID)",
          "Chediak Higashi syndrome"
        ],
        "answer": "Chronic granulomatous disease"
      },
      {
        "question": "Chronic inflammatory mediator is:",
        "options": [
          "IL-1",
          "IL-6",
          "TNF-alpha",
          "TGF-beta"
        ],
        "answer": "TNF-alpha"
      },
      {
        "question": "All are features of irreversible injury, except?",
        "options": [
          "PECAM-1",
          "IL-6",
          "Integrin",
          "TGF-beta"
        ],
        "answer": "IL-6"
      },
      {
        "question": "Dystrophic calcification is seen in:",
        "options": [
          "Hyperparathyroidism",
          "Atherosclerosis",
          "Lymphoreticular malignancy",
          "Densities in mitochondria"
        ],
        "answer": "Atherosclerosis"
      },
      {
        "question": "Which of the following molecules are required for adhesion of leukocyte to vascular endothelial cells in acute inflammation?",
        "options": [
          "Selectins",
          "Integrins",
          "Fibronectin",
          "PECAM-1"
        ],
        "answer": "Selectins"
      },
      {
        "question": "A patient undergoes a surgery on the anterior chest wall. Post-surgery, he notices a lesion having itching and present within the margins of the wound in the pre-sternal area. What is the most likely diagnosis?",
        "options": [
          "Lipoma",
          "Keloid",
          "Hypertrophic scar",
          "Normal granulation tissue"
        ],
        "answer": "Keloid"
      },
      {
        "question": "What is the location of lactate dehydrogenase inside the cell?",
        "options": [
          "Nucleus",
          "Mitochondria",
          "Cytosol",
          "Endoplasmic reticulum"
        ],
        "answer": "Cytosol"
      },
      {
        "question": "Lysosomal enzymes are presented in:",
        "options": [
          "Hemosiderin",
          "Melanin",
          "Endoplasmic reticulum",
          "Nucleus"
        ],
        "answer": "Endoplasmic reticulum"
      },
      {
        "question": "An 83-year-old man shows presence of perinuclear pigment in the cardiac muscle fibers. What is the nature of the pigment?",
        "options": [
          "Formalin",
          "Lipofuscin",
          "Iron",
          "Glutaraldehyde"
        ],
        "answer": "Lipofuscin"
      },
      {
        "question": "Macrophages play an important role in phagocytosis and chronic inflammation. Which of the following cells perform the same function in the liver?",
        "options": [
          "Merkel cell",
          "Kupfer cell",
          "Glutaraldehyde",
          "Cytoplasm"
        ],
        "answer": "Kupfer cell"
      },
      {
        "question": "A patient died of myocardial infarction and his heart was taken out and immersed in a solution. The normal area of the heart turned brick red, whereas the infarcted portion turned white. Which of the following can be the likely component of the solution?",
        "options": [
          "Triphenyl tetrazolium chloride",
          "Mitochondria",
          "Ribosomes",
          "Ethanol"
        ],
        "answer": "Triphenyl tetrazolium chloride"
      },
      {
        "question": "Stellate granuloma is found in:",
        "options": [
          "Granuloma formation",
          "Granulation tissue",
          "Hofbauer cell",
          "Stellate cells"
        ],
        "answer": "Stellate cells"
      },
      {
        "question": "Secondary healing mechanism is:",
        "options": [
          "Scab formation",
          "Neovascularization",
          "Leprosy",
          "Histoplasmosis"
        ],
        "answer": "Neovascularization"
      },
      {
        "question": "Rolling of leukocytes on endothelial cells is mediated by:",
        "options": [
          "Selectins",
          "Integrins",
          "PECAM-1",
          "G1S"
        ],
        "answer": "Selectins"
      },
      {
        "question": "p53 regulates which phase of cell cycle?",
        "options": [
          "G1",
          "G2",
          "S",
          "M"
        ],
        "answer": "G1"
      },
      {
        "question": "Proapoptotic gene and anti-apoptotic gene belong to which gene family?",
        "options": [
          "p53",
          "Bcl",
          "Rb",
          "BRAF"
        ],
        "answer": "Bcl"
      },
      {
        "question": "DNA synthesis is seen in which phase of cell cycle?",
        "options": [
          "Resting phase",
          "Synthetic phase",
          "Mitotic phase",
          "Premittic phase"
        ],
        "answer": "Synthetic phase"
      },
      {
        "question": "Councilman bodies are formed due to which process?",
        "options": [
          "Necrosis",
          "Apoptosis",
          "Hydropic degeneration",
          "Fatty degeneration"
        ],
        "answer": "Necrosis"
      },
      {
        "question": "Which of the following is an opsonin?",
        "options": [
          "Interleukins",
          "E-Cadherin",
          "Defensin",
          "Complement"
        ],
        "answer": "Complement"
      },
      {
        "question": "Which of the following helps in cell-to-cell adhesion?",
        "options": [
          "Dysplasia",
          "Hyperplasia",
          "Metaplasia",
          "Atrophy"
        ],
        "answer": "Metaplasia"
      },
      {
        "question": "A reversible change occurring in which a mature cell type is replaced by another mature cell is called:",
        "options": [
          "Hypertrophy",
          "Hyperplasia",
          "Atrophy",
          "Metaplasia"
        ],
        "answer": "Metaplasia"
      },
      {
        "question": "A patient who was previously with good muscle mass now presents with decreased muscle mass. There is a history of RTA, which led him to be bedridden for 6 months. This decrease in muscle mass is best explained by:",
        "options": [
          "Hyperplasia",
          "Atrophy",
          "Hypertrophy",
          "Metaplasia"
        ],
        "answer": "Atrophy"
      },
      {
        "question": "A pregnant uterus is an example of:",
        "options": [
          "Dysplasia",
          "Hypertrophy",
          "Metaplasia",
          "Atrophy"
        ],
        "answer": "Hypertrophy"
      },
      {
        "question": "In individuals who donate one lobe of the liver for transplantation, the remaining organ soon grows back to its original size. This is an example of which adaptive mechanism?",
        "options": [
          "Metaplasia",
          "Hyperplasia",
          "Hypertrophy",
          "Atrophy"
        ],
        "answer": "Hyperplasia"
      },
      {
        "question": "Apoptosis is inhibited by:",
        "options": [
          "Bcl-2",
          "Bad",
          "Transglutaminase",
          "Atrophy"
        ],
        "answer": "Bcl-2"
      },
      {
        "question": "All are true about apoptosis, except?",
        "options": [
          "Apoptotic cells appear as round mass with eosinophilic cytoplasm",
          "Apoptosis induces inflammatory reaction",
          "Apoptotic cells show condensation of chromatin",
          "Apoptotic cells show normal chromatin"
        ],
        "answer": "Apoptotic cells show normal chromatin"
      },
      {
        "question": "In apoptosis, protein hydrolysis is due to activation of:",
        "options": [
          "Caspases",
          "Bax",
          "P53",
          "Catalase"
        ],
        "answer": "Caspases"
      },
      {
        "question": "Caspases are associated with which of the following?",
        "options": [
          "Collagen hyalinization",
          "Hydropic degeneration",
          "Embryogenesis",
          "Fatty degeneration"
        ],
        "answer": "Collagen hyalinization"
      },
      {
        "question": "Which of the following types of necrosis is most commonly associated with ischemic injury?",
        "options": [
          "Coagulative necrosis",
          "Fat necrosis",
          "Liquefactive necrosis",
          "Caseous necrosis"
        ],
        "answer": "Coagulative necrosis"
      },
      {
        "question": "All are true about amoebiasis, EXCEPT:",
        "options": [
          "Flask shaped ulcers",
          "Disease affects cecum and ascending colon",
          "Anchovy pus in liver",
          "Coagulative necrosis"
        ],
        "answer": "Coagulative necrosis"
      },
      {
        "question": "Integrins include receptor; EXCEPT?",
        "options": [
          "Fibronectin",
          "Glycoprotein on platelet surface",
          "Leukocyte adhesion molecule",
          "Platelet-derived growth factor"
        ],
        "answer": "Platelet-derived growth factor"
      },
      {
        "question": "Exudation of plasma and leucocytes in acute inflammation is from?",
        "options": [
          "Venules",
          "Arterioles",
          "Arterioles and capillaries",
          "Capillaries"
        ],
        "answer": "Venules"
      },
      {
        "question": "Digestion of foreign material by a neutrophil or macrophage during phagocytosis is mainly due to?",
        "options": [
          "Complement",
          "Kinins",
          "Superoxide dismutase",
          "Catalase"
        ],
        "answer": "Superoxide dismutase"
      },
      {
        "question": "Which of the following is a peroxisomal free radical scavenger?",
        "options": [
          "Vasoconstriction",
          "Stasis",
          "Superoxide dismutase",
          "Catalase"
        ],
        "answer": "Superoxide dismutase"
      },
      {
        "question": "Which among the following is the hallmark of acute inflammation?",
        "options": [
          "Tumor necrosis factor",
          "Interferons",
          "Vasodilation and increase in permeability",
          "Exudation"
        ],
        "answer": "Exudation"
      },
      {
        "question": "Which of the following is not an inflammatory mediator?",
        "options": [
          "NADPH oxidase",
          "Margination",
          "Capillaries",
          "Catalase"
        ],
        "answer": "Margination"
      },
      {
        "question": "All of the following host tissue responses can be seen in acute infection, EXCEPT:",
        "options": [
          "Vitamin B1",
          "Glutathione peroxidase",
          "Lysosomal enzymes",
          "Beta-carotene"
        ],
        "answer": "All of these"
      },
      {
        "question": "Oxygen-dependent killing is done through?",
        "options": [
          "Pancreas",
          "Myeloperoxidase",
          "Interleukin",
          "Superoxide dismutase"
        ],
        "answer": "Myeloperoxidase"
      },
      {
        "question": "Which of the following is required for post-translational modification?",
        "options": [
          "Eosinophils",
          "Superoxide dismutase",
          "Glutathione peroxidase",
          "Fibrosis"
        ],
        "answer": "Superoxide dismutase"
      },
      {
        "question": "Fat necrosis occurs at all sites, EXCEPT:",
        "options": [
          "Biotin",
          "Vitamin C",
          "Liver",
          "Peritoneum"
        ],
        "answer": "Vitamin C"
      },
      {
        "question": "Morphological changes seen in chronic nonspecific inflammation include an increase in:",
        "options": [
          "Neutrophils, lymphocytes and liquefactive necrosis",
          "Neutrophils, macrophages and fibrosis",
          "Lymphocytes, plasma cells and fibrosis",
          "Giant cells, macrophages and coagulative necrosis"
        ],
        "answer": "Lymphocytes, plasma cells and fibrosis"
      },
      {
        "question": "Foci of granulomatous inflammation show all of the following; EXCEPT?",
        "options": [
          "Epithelioid cells",
          "Lymphocytes",
          "Granulation tissue",
          "Giant cells"
        ],
        "answer": "Lymphocytes"
      },
      {
        "question": "All of the following are true in respect of angioneurotic edema; EXCEPT:",
        "options": [
          "It is caused by deficiency of complement proteins",
          "It is more common in females",
          "It manifests as pitting edema",
          "It is an autosomal dominant disorder"
        ],
        "answer": "It is caused by deficiency of complement proteins"
      },
      {
        "question": "Which is the most abundant plasma protein?",
        "options": [
          "Albumin",
          "Fibrinogen",
          "Transferrin",
          "Globulin"
        ],
        "answer": "Albumin"
      },
      {
        "question": "All are true about components of Virchow's triad, EXCEPT:",
        "options": [
          "Vasculitis",
          "Stasis in veins",
          "White thrombus",
          "Increased protein C"
        ],
        "answer": "Vasculitis"
      },
      {
        "question": "All are true about arterial thrombosis, EXCEPT:",
        "options": [
          "Retrograde growth",
          "Mesentery",
          "Complete lumen obstruction",
          "Thrombosis"
        ],
        "answer": "Retrograde growth"
      },
      {
        "question": "Which is the most common site of arterial embolization?",
        "options": [
          "Brain",
          "Kidney",
          "Liver",
          "Spleen"
        ],
        "answer": "Brain"
      },
      {
        "question": "Chicken fat appearance is seen in:",
        "options": [
          "Antemortem clots",
          "Fat necrosis",
          "Bence Jones protein",
          "Coagulative necrosis"
        ],
        "answer": "Fat necrosis"
      },
      {
        "question": "All are true about white infarcts, EXCEPT:",
        "options": [
          "Edema is present",
          "Occurs in organs with end arterial supply",
          "Lower extremities",
          "Well-defined margins"
        ],
        "answer": "Well-defined margins"
      }
    ],
    "Neoplasia": [
      {
        "question": "A 25-year-old male with dragging sensation in groin. On examination, a testicular mass is identified which was resected. What is the most likely diagnosis?",
        "options": [
          "Seminoma",
          "Teratoma",
          "Yolk sac tumor",
          "Testicular torsion"
        ],
        "answer": "Seminoma"
      },
      {
        "question": "A 23-year-old woman discovers a well-defined, mobile, and rubbery breast lump measuring 3 x 3 cm on self-examination. The lesion is painless and has been stable over several months. What is the most likely diagnosis based on the described characteristics?",
        "options": [
          "DCIS",
          "Invasive ductal carcinoma",
          "Fibroadenoma",
          "Intraductal papilloma"
        ],
        "answer": "Fibroadenoma"
      },
      {
        "question": "Primary effusion lymphoma is caused by:",
        "options": [
          "HHV-8",
          "Hepadnavirus",
          "Chloroma",
          "Ewing's sarcoma"
        ],
        "answer": "HHV-8"
      },
      {
        "question": "A young boy presents with a small round cell tumor of the eye. What is the diagnosis?",
        "options": [
          "Retinoblastoma",
          "Neuroblastoma",
          "Optic glioma",
          "Medulloblastoma"
        ],
        "answer": "Retinoblastoma"
      },
      {
        "question": "Which of the following subtypes of breast cancer has the best prognosis?",
        "options": [
          "Luminal A",
          "Luminal B",
          "Triple negative breast cancer",
          "HER2-positive"
        ],
        "answer": "Luminal A"
      },
      {
        "question": "Which of the following tumors arises from all three germ layers?",
        "options": [
          "Teratoma",
          "Yolk sac tumor",
          "Seminoma",
          "Choristoma"
        ],
        "answer": "Teratoma"
      },
      {
        "question": "A 40-year-old man having a well-circumscribed testicular swelling undergoes orchiectomy, which on further evaluation has OCT4+ tissue. What is the most likely diagnosis?",
        "options": [
          "Rhabdomyosarcoma",
          "Testicular seminoma",
          "Congenital cataract",
          "Carcinoma prostate"
        ],
        "answer": "Testicular seminoma"
      },
      {
        "question": "A child presented with leukocoria and strabismus. What is the likely diagnosis?",
        "options": [
          "Retinoblastoma",
          "Neuroblastoma",
          "Wilms tumor",
          "Glioma"
        ],
        "answer": "Retinoblastoma"
      },
      {
        "question": "A 60-year-old male presents with low back pain. X-ray of the LS spine shows osteoblastic changes. What is the likely diagnosis?",
        "options": [
          "Prostate cancer",
          "Metastatic lung cancer",
          "Pott spine",
          "Multiple myeloma"
        ],
        "answer": "Prostate cancer"
      },
      {
        "question": "Which of the following is a tumor marker for pancreatic cancer?",
        "options": [
          "CA 19-9",
          "CA 15-3",
          "AFP",
          "CEA"
        ],
        "answer": "CA 19-9"
      },
      {
        "question": "Which of the following contributes to the immortality of cancer cells?",
        "options": [
          "Telomerase",
          "Cyclin D",
          "p53",
          "Rb"
        ],
        "answer": "Telomerase"
      },
      {
        "question": "A patient has been diagnosed with a condition due to a DNA repair gene defect. He is having mottled hyperpigmentation on the skin and is at high risk for developing skin cancers. Which of the following is a likely enzyme defect in this patient?",
        "options": [
          "Helicase",
          "Nucleotide excision repair defect",
          "ATN gene",
          "MSH gene"
        ],
        "answer": "Nucleotide excision repair defect"
      },
      {
        "question": "Which is the most common tumor of the mediastinum?",
        "options": [
          "Thymoma",
          "Neurogenic tumor",
          "Teratoma",
          "Lymphoma"
        ],
        "answer": "Thymoma"
      },
      {
        "question": "Most common anterior mediastinal tumor?",
        "options": [
          "Thymoma",
          "Pericardial cyst",
          "Neurofibroma",
          "Lymphoma"
        ],
        "answer": "Thymoma"
      },
      {
        "question": "Which of the following is true about anaplasia?",
        "options": [
          "Loss of cohesion between cells",
          "Totipotent",
          "Pluripotent",
          "Benign and fully reversible"
        ],
        "answer": "Loss of cohesion between cells"
      },
      {
        "question": "A cell that can form any other cell in the body is called:",
        "options": [
          "Stem cell",
          "Totipotent cell",
          "Pluripotent cell",
          "Multipotent cell"
        ],
        "answer": "Totipotent cell"
      },
      {
        "question": "Which is the most common cancer resulting in death?",
        "options": [
          "Lung cancer",
          "Prostate cancer",
          "Breast cancer",
          "Pancreatic cancer"
        ],
        "answer": "Lung cancer"
      },
      {
        "question": "Which of the following cancers is not due to an infectious etiology?",
        "options": [
          "Small cell lung cancer",
          "Hepatocellular carcinoma",
          "Nasopharyngeal cancer",
          "MALT lymphoma"
        ],
        "answer": "Small cell lung cancer"
      },
      {
        "question": "Most common middle mediastinal tumor?",
        "options": [
          "Bronchogenic cyst",
          "Lymphoma",
          "Neurofibroma",
          "Germ cell tumor"
        ],
        "answer": "Bronchogenic cyst"
      },
      {
        "question": "Which of the following lesions is caused by HPV?",
        "options": [
          "Genital warts",
          "Oral cancer",
          "Anal carcinoma",
          "Nasopharyngeal carcinoma"
        ],
        "answer": "Genital warts"
      },
      {
        "question": "In a FAP (Familial Adenomatous Polyposis) patient, which is an important cancer risk?",
        "options": [
          "Colorectal cancer",
          "Breast cancer",
          "Endometrial cancer",
          "Ovarian cancer"
        ],
        "answer": "Colorectal cancer"
      },
      {
        "question": "Esophageal irradiation causes damage by:",
        "options": [
          "Decreasing secretion",
          "Stricture formation",
          "Ulceration",
          "Adenocarcinoma"
        ],
        "answer": "Stricture formation"
      },
      {
        "question": "Tongue cancer is NOT seen with:",
        "options": [
          "Breast cancer",
          "Pericardial cyst",
          "Thyroid cancer",
          "Lymphoma"
        ],
        "answer": "Pericardial cyst"
      },
      {
        "question": "Most radiosensitive tumor is:",
        "options": [
          "Ewing’s sarcoma",
          "Glioblastoma",
          "Seminoma",
          "Brain tumor"
        ],
        "answer": "Seminoma"
      },
      {
        "question": "Radiation exposure during infancy has been linked to which carcinoma?",
        "options": [
          "Lymphoid cancer",
          "Thyroid cancer",
          "Leukemia",
          "Breast cancer"
        ],
        "answer": "Thyroid cancer"
      },
      {
        "question": "UV radiation has which of the following effects on the cells?",
        "options": [
          "Prevents formation of pyrimidine dimers",
          "Stimulates formation of pyrimidine dimers",
          "Prevents formation of purine dimers",
          "All of the above"
        ],
        "answer": "Stimulates formation of pyrimidine dimers"
      },
      {
        "question": "The most radiosensitive cells are:",
        "options": [
          "Neutrophils",
          "Lymphocytes",
          "Erythrocytes",
          "Megakaryocytes"
        ],
        "answer": "Lymphocytes"
      },
      {
        "question": "The following parasitic infections predispose to malignancy, EXCEPT:",
        "options": [
          "Paragonimus westermani",
          "Guinea worm infection",
          "Clonorchiasis",
          "Ancyclostoma"
        ],
        "answer": "Guinea worm infection"
      }
    ],
    "cardiology": [
      {
        "question": "A patient died due to MI. Which stain is used to see the infarct portion of heart?",
        "options": [
          "Prussian blue",
          "Triphenyl tetrazolium chloride",
          "Hematoxylin",
          "Wright's stain"
        ],
        "answer": "Triphenyl tetrazolium chloride"
      },
      {
        "question": "An 8-year-old patient presents with abdominal pain, rashes on legs, and difficulty in walking. First differential diagnosis is:",
        "options": [
          "IgA nephropathy",
          "Meningococcemia",
          "Henoch-Schönlein purpura",
          "Rheumatic fever"
        ],
        "answer": "Henoch-Schönlein purpura"
      },
      {
        "question": "Most common cardiac defect in Down syndrome is:",
        "options": [
          "Endocardial cushion defect",
          "Ventricular septal defect",
          "Peripheral pulmonic stenosis",
          "Anomalous origin of left coronary artery from pulmonary artery (A.L.C.A.P.A)"
        ],
        "answer": "Endocardial cushion defect"
      },
      {
        "question": "Histopathological finding 12 hours after ischemic injury to the heart is:",
        "options": [
          "Karyorhexis of myocytes",
          "Neo-capillary invasion of myocytes",
          "Hyper-eosinophilia of myocytes",
          "Coagulation necrosis of myocytes"
        ],
        "answer": "Coagulation necrosis of myocytes"
      },
      {
        "question": "Which of the following is the correct description for the type of heart lesion seen in patients of rheumatic heart disease?",
        "options": [
          "Cardiac failure",
          "Mural thrombus",
          "Aschoff's nodules",
          "Pericarditis"
        ],
        "answer": "Aschoff's nodules"
      },
      {
        "question": "Which is the most common cause of death in rheumatic heart disease?",
        "options": [
          "Neutrophilic infiltration",
          "Coagulative necrosis",
          "Fibrovascular response",
          "Myxomatous degeneration"
        ],
        "answer": "Coagulative necrosis"
      },
      {
        "question": "Which is the earliest histopathological change in myocardial infarction?",
        "options": [
          "Myxoma",
          "McCallum patch",
          "Stretching and waviness of fibers",
          "Myxomatous degeneration"
        ],
        "answer": "Stretching and waviness of fibers"
      },
      {
        "question": "Most common primary cardiac tumor?",
        "options": [
          "Myxoma",
          "Rhabdomyoma",
          "Angiosarcoma",
          "Rhabdomyosarcoma"
        ],
        "answer": "Myxoma"
      },
      {
        "question": "Which of the following is pathognomonic for rheumatic fever?",
        "options": [
          "Anitschkow cells",
          "Vegetations along the cusps",
          "Osler's nodes",
          "McCallum's patch"
        ],
        "answer": "Anitschkow cells"
      },
      {
        "question": "All are true about myocardial response and changes to myocardial infarction, EXCEPT:",
        "options": [
          "Neutrophilic infiltrates in the first 48 hours",
          "Loss of contractility within 2 minutes",
          "Reversible injury within 20-40 minutes",
          "Waviness of fibers at border of infarct"
        ],
        "answer": "Reversible injury within 20-40 minutes"
      },
      {
        "question": "Which is Incorrect about Buerger's disease?",
        "options": [
          "Ischemia of nerves",
          "Deep vein thrombosis",
          "Segmental inflammation",
          "Superficial thrombophlebitis"
        ],
        "answer": "Deep vein thrombosis"
      },
      {
        "question": "Why is Troponin C not used for MI diagnosis?",
        "options": [
          "Troponin C binds to calcium",
          "Troponin C is present in both cardiac and smooth muscle",
          "Troponin C is present in both cardiac and skeletal muscle",
          "It elevates late after onset of MI"
        ],
        "answer": "Troponin C is present in both cardiac and skeletal muscle"
      },
      {
        "question": "Postmortem findings of myocardial infarction are all; EXCEPT:",
        "options": [
          "Coagulative necrosis",
          "Glycogen depletion",
          "Granulation with type 4 collagen",
          "Loss of nuclei"
        ],
        "answer": "Glycogen depletion"
      },
      {
        "question": "Fibrinoid necrosis may be observed in all of the following, EXCEPT:",
        "options": [
          "Malignant hypertension",
          "Polyarteritis nodosa",
          "Diabetic glomerulosclerosis",
          "Aschoff's nodule"
        ],
        "answer": "Aschoff's nodule"
      },
      {
        "question": "Polyarteritis Nodosa (PAN) typically involves which of the following?",
        "options": [
          "Large elastic arteries",
          "Small- or medium-sized muscular arteries",
          "Arterioles",
          "Capillaries"
        ],
        "answer": "Small- or medium-sized muscular arteries"
      },
      {
        "question": "All are examples of medium vessel vasculitis, EXCEPT:",
        "options": [
          "Classic PAN",
          "Kawasaki disease",
          "Buerger disease",
          "SLE"
        ],
        "answer": "SLE"
      },
      {
        "question": "A 45-year-old patient working in a factory for the past 20 years presents with breathlessness. HRCT chest shows pleural thickening and fibrosis. Diagnosis is:",
        "options": [
          "Asbestosis",
          "Coal worker pneumoconiosis",
          "Silicosis",
          "Berylliosis"
        ],
        "answer": "Asbestosis"
      },
      {
        "question": "Curschmann spirals are characteristic of which of the following airway diseases?",
        "options": [
          "Asthma",
          "Bronchitis",
          "Emphysema",
          "Pulmonary fibrosis"
        ],
        "answer": "Asthma"
      },
      {
        "question": "Simmond focus in tuberculosis is seen in?",
        "options": [
          "Lungs",
          "Liver",
          "Brain",
          "Kidneys"
        ],
        "answer": "Lungs"
      },
      {
        "question": "All are true about chronic bronchitis, EXCEPT:",
        "options": [
          "Egg shell calcification",
          "Submucosal gland hypertrophy",
          "Eosinophilic infiltration of airways",
          "Bronchorrhea"
        ],
        "answer": "Bronchorrhea"
      },
      {
        "question": "All are true about silicosis, EXCEPT:",
        "options": [
          "Quartz is the main form implicated in pathogenesis",
          "Nodular fibrosis",
          "Triphenyl tetrazolium chloride",
          "Chronic blood loss"
        ],
        "answer": "Chronic blood loss"
      },
      {
        "question": "A 50-year-old chronic smoker presents with intermittent claudication of the legs. Initially, the pain was experienced during activity, but now, he also experiences pain at rest. What is this condition known as?",
        "options": [
          "Takayasu arteritis",
          "Buerger's disease",
          "Peripheral arterial disease",
          "Raynaud's phenomenon"
        ],
        "answer": "Buerger's disease"
      },
      {
        "question": "A 60-year-old patient presents with throbbing unilateral headache and nodular thickening along with the temporal artery. Microscopic examination reveals giant cells and granulomas. What is the most likely diagnosis?",
        "options": [
          "Temporal arteritis",
          "HSP",
          "Berger's disease",
          "Giant cell arteritis"
        ],
        "answer": "Temporal arteritis"
      },
      {
        "question": "A chronic cigarette smoker presented with pain and black necrotic fingers as shown. What is the most likely diagnosis?",
        "options": [
          "Thromboangiitis obliterans",
          "Temporal arteritis",
          "HSP",
          "Deep vein thrombosis"
        ],
        "answer": "Thromboangiitis obliterans"
      },
      {
        "question": "Schaumann body is seen in cases of:",
        "options": [
          "Silicosis",
          "Sarcoidosis",
          "Pleural plaque",
          "Interstitial calcification"
        ],
        "answer": "Sarcoidosis"
      },
      {
        "question": "Which is the most common clinical presentation of sarcoidosis?",
        "options": [
          "Pulmonary fibrosis",
          "Hilar lymphadenopathy",
          "Interstitial calcification",
          "Pleural plaque"
        ],
        "answer": "Hilar lymphadenopathy"
      },
      {
        "question": "Lung cancer is most commonly associated with:",
        "options": [
          "Silicosis",
          "Berylliosis",
          "Asbestosis",
          "Small cell lung cancer"
        ],
        "answer": "Asbestosis"
      },
      {
        "question": "Which is the most common type of lung cancer?",
        "options": [
          "Squamous cell carcinoma",
          "Adenocarcinoma",
          "Small cell lung carcinoma",
          "Large cell carcinoma"
        ],
        "answer": "Adenocarcinoma"
      },
      {
        "question": "Which is the most aggressive lung cancer?",
        "options": [
          "Mesothelioma",
          "Adenocarcinoma lung",
          "Squamous cell carcinoma",
          "Large cell carcinoma"
        ],
        "answer": "Squamous cell carcinoma"
      },
      {
        "question": "Which is the most common cancer associated with asbestosis?",
        "options": [
          "SLE",
          "Asbestosis",
          "Squamous cell cancer of the lung",
          "Polyarteritis Nodosa"
        ],
        "answer": "Squamous cell cancer of the lung"
      },
      {
        "question": "Hypersensitivity angiitis is seen in:",
        "options": [
          "Buerger's disease",
          "Henoch-Schönlein purpura",
          "Polyarteritis Nodosa",
          "Anthracosis"
        ],
        "answer": "Henoch-Schönlein purpura"
      }
    ],
    "Immunity and hypersenstivity": [
      {
        "question": "Which of the following organs is a primary lymphoid organ?",
        "options": [
          "Spleen",
          "Liver",
          "Thymus",
          "Bone marrow"
        ],
        "answer": "Thymus"
      },
      {
        "question": "Graft rejection is seen maximum with which organ?",
        "options": [
          "Heart",
          "Lungs",
          "Kidney",
          "Intestine"
        ],
        "answer": "Kidney"
      },
      {
        "question": "Cells responsible for chronic graft rejection are:",
        "options": [
          "NK cells",
          "T cells",
          "B cells",
          "Plasma cells"
        ],
        "answer": "T cells"
      },
      {
        "question": "Myasthenia gravis is which type of hypersensitivity reaction?",
        "options": [
          "Type I",
          "Type II",
          "Type III",
          "Type IV"
        ],
        "answer": "Type II"
      },
      {
        "question": "Rh incompatibility is which type of hypersensitivity reaction?",
        "options": [
          "Type I",
          "Type II",
          "Type III",
          "Type IV"
        ],
        "answer": "Type II"
      },
      {
        "question": "A child got stung by a honey-bee while playing. After that, the child presented with hypotension, edema, and breathlessness. Which of the following antibody is responsible for this?",
        "options": [
          "IgA",
          "IgG",
          "IgE",
          "IgM"
        ],
        "answer": "IgE"
      },
      {
        "question": "A child presented with thymic hypoplasia, decreased immunity, and hypocalcemia. He also has tetralogy of Fallot. What is the diagnosis?",
        "options": [
          "Di-George syndrome",
          "Wiskott-Aldrich syndrome",
          "SCID",
          "Folate deficiency"
        ],
        "answer": "Di-George syndrome"
      },
      {
        "question": "Which of the following causes SCID?",
        "options": [
          "Deficiency of adenosine deaminase",
          "Deficiency of tyrosine kinase",
          "Vitamin B12 deficiency",
          "NK cell"
        ],
        "answer": "Deficiency of adenosine deaminase"
      },
      {
        "question": "The cell given in lymph node biopsy shows origin from which of the following cell lines?",
        "options": [
          "CD4 cells",
          "CD8 cells",
          "B cells",
          "T cells"
        ],
        "answer": "CD4 cells"
      },
      {
        "question": "A boy presents in the emergency with allergy due to pollen inhalation. Which of the following cells is important in the pathogenesis of this condition?",
        "options": [
          "NK cells",
          "Neutrophils",
          "Helper T cells",
          "B cells"
        ],
        "answer": "Helper T cells"
      },
      {
        "question": "A 55-year-old patient presented with difficulty in breathing and rashes after ingesting seafood. He has shown similar reactions in the past following consumption of the same food items. Which of the following hypersensitivity reactions is present in this case?",
        "options": [
          "Type I",
          "Type II",
          "Type III",
          "Type IV"
        ],
        "answer": "Type I"
      },
      {
        "question": "A 47-year-old female presented with arthralgia, difficulty in swallowing food, and a gritty feeling in the eyes. She also has increased titers of ANA. Which of the following is the likely diagnosis?",
        "options": [
          "Sjogren's syndrome",
          "Serum sickness",
          "Rheumatoid arthritis",
          "Systemic lupus erythematosus"
        ],
        "answer": "Sjogren's syndrome"
      },
      {
        "question": "An elderly diabetic male patient underwent kidney transplantation from his twin brother. The type of grafting is:",
        "options": [
          "Allograft",
          "Isograft",
          "Autograft",
          "Xenograft"
        ],
        "answer": "Isograft"
      },
      {
        "question": "A 56-year-old diabetic patient has chronic renal failure and is undergoing hemodialysis. Which of the following amyloid is most likely to get deposited?",
        "options": [
          "Toll-like receptor",
          "MHC",
          "Beta-2 microglobulin",
          "Serum amyloid A"
        ],
        "answer": "Beta-2 microglobulin"
      },
      {
        "question": "A 30-year-old woman is having progressive dysphagia. On examination, she has thickening of oral mucosa and leather-like skin. She is also hypertensive and has limited exercise capacity due to lung fibrosis. Which of the following is the possible diagnosis?",
        "options": [
          "Peutz-Jeghers syndrome",
          "Post cricoid dysphagia",
          "Achalasia cardia",
          "Scleroderma"
        ],
        "answer": "Scleroderma"
      },
      {
        "question": "Which of the following is the molecule required for presentation of the antigens by an antigen-presenting cell to the TH2 cell?",
        "options": [
          "Lectin receptor",
          "G protein-coupled receptor",
          "CD4",
          "Cytotoxic T cell"
        ],
        "answer": "Lectin receptor"
      },
      {
        "question": "Acute graft rejection occurs within:",
        "options": [
          "Minutes",
          "Hours",
          "Days to weeks",
          ">6 weeks to 6 months"
        ],
        "answer": "Hours"
      },
      {
        "question": "Which of the following is a causative agent of Farmer's lung?",
        "options": [
          "Thermophilic Actinomycetes",
          "Aspergillus Fumigatus",
          "Aspergillus Flavus",
          "Actinobacter"
        ],
        "answer": "Thermophilic Actinomycetes"
      },
      {
        "question": "First line of defense against tumor and virus?",
        "options": [
          "NK cells",
          "T cells",
          "Macrophages",
          "B cells"
        ],
        "answer": "NK cells"
      },
      {
        "question": "Type II hypersensitivity is seen in:",
        "options": [
          "Pernicious anemia",
          "Serum sickness",
          "Arthus phenomenon",
          "Pathergy phenomenon"
        ],
        "answer": "Pernicious anemia"
      },
      {
        "question": "Acute graft rejection occurs within?",
        "options": [
          "Minutes",
          "Hours",
          "Days to weeks",
          ">6 weeks to 6 months"
        ],
        "answer": "Minutes"
      },
      {
        "question": "Neonatal lupus is screened by which antibody?",
        "options": [
          "Anti-Ro",
          "Anti-Sm",
          "Anti-dsDNA",
          "Anti-phospholipid"
        ],
        "answer": "Anti-Ro"
      },
      {
        "question": "Which is not an antigen-presenting cell?",
        "options": [
          "T cell",
          "Macrophage",
          "Dendritic cell",
          "Follicular dendritic cell"
        ],
        "answer": "T cell"
      },
      {
        "question": "In graft rejection, which type of HLA is involved?",
        "options": [
          "MHC class I",
          "MHC class II",
          "MHC class III",
          "MHC class IV"
        ],
        "answer": "MHC class II"
      }
    ],
    "Haematology": [
      {
        "question": "A 45-year-old patient presents with complaints of weakness and fatigue. Laboratory work up shows low Hb and high reticulocyte count. WBC and platelet count are within normal limits. Bone marrow aspiration shows erythroid hyperplasia. Based on the information above what is the likely diagnosis?",
        "options": [
          "Aplastic anemia",
          "Pure red cell aplasia",
          "Hemolytic anemia",
          "Iron deficiency anemia"
        ],
        "answer": "Aplastic anemia"
      },
      {
        "question": "Splenectomy is indicated in which of the following hemolytic anemias?",
        "options": [
          "Hereditary spherocytosis",
          "G6PD deficiency",
          "Iron deficiency anemia",
          "Vitamin B12 deficiency anemia"
        ],
        "answer": "Hereditary spherocytosis"
      },
      {
        "question": "A 10-year-old child is brought in with a history of repeated blood transfusions in the past. Mother is worried about her son, as his grades are deteriorating and he remains lethargic and extremely pale. Blood investigations show crescent-shaped red blood cells. What should be the next step in management?",
        "options": [
          "IV antibiotics",
          "Blood transfusion",
          "Normal saline",
          "TIBC"
        ],
        "answer": "Blood transfusion"
      },
      {
        "question": "A child visited the hospital with complaints of severe fatigue, lethargy, pallor, and irritation. He is a known case of IDA and on oral iron supplements. After review, doctors are planning to start with IV iron supplementation. What test should be done next?",
        "options": [
          "ALL",
          "CML",
          "Hb value",
          "Iron studies"
        ],
        "answer": "Iron studies"
      },
      {
        "question": "A 60-year-old man presents with a 2-month history of weakness and pallor. Per abdomen shows moderate splenomegaly. Peripheral blood shows Hb = 10 g/dL, leucocytosis, and platelets 3 lac/µl. P. smear shows metamyelocytes 15%, promyeloblasts 30%, myeloblasts 45%. Which of the following is the diagnosis?",
        "options": [
          "Sideroblastic anemia",
          "Thalassemia",
          "Multiple myeloma",
          "AML"
        ],
        "answer": "AML"
      },
      {
        "question": "A patient is suffering from iron deficiency anemia. What stain shall be used on the bone marrow specimen to confirm iron store depletion?",
        "options": [
          "Alizarin red",
          "Prussian blue",
          "Methylene blue",
          "Von Kossa"
        ],
        "answer": "Prussian blue"
      },
      {
        "question": "Macrocytic anemia will be seen in:",
        "options": [
          "Anemia of chronic disease",
          "Megaloblastic anemia",
          "Chronic liver disease",
          "Hemolytic anemia"
        ],
        "answer": "Megaloblastic anemia"
      },
      {
        "question": "A 65-year-old man presents with hypercalcemia and deranged KFT. Workup shows Hb is low, TLC is elevated, and X-ray skull shows multiple lytic lesions. What is the diagnosis?",
        "options": [
          "HIV 1,2",
          "CLL",
          "Multiple myeloma",
          "AML"
        ],
        "answer": "Multiple myeloma"
      },
      {
        "question": "Testing for which of the following infections is not done before giving blood transfusion?",
        "options": [
          "Hep B",
          "Hep C",
          "Hep A",
          "HIV"
        ],
        "answer": "Hep A"
      },
      {
        "question": "Most common anemia in a 65-year-old patient?",
        "options": [
          "Iron deficiency anemia",
          "Anemia of chronic disease",
          "Sickle cell anemia",
          "Megaloblastic anemia"
        ],
        "answer": "Anemia of chronic disease"
      },
      {
        "question": "What blood group should be given to a Bombay blood group patient?",
        "options": [
          "AB",
          "O positive",
          "O negative",
          "O positive"
        ],
        "answer": "O negative"
      },
      {
        "question": "A 27-year-old pregnant female is on a vegetarian diet. What kind of anemia could she develop?",
        "options": [
          "Macrocytic anemia",
          "Sideroblastic anemia",
          "Iron deficiency anemia",
          "Anemia of chronic disease"
        ],
        "answer": "Iron deficiency anemia"
      },
      {
        "question": "A patient came to the OPD with a complaint of fatigue. Significant pallor is noted in conjunctiva and palms. Investigations show Hb = 5.8 g/dL, low ferritin, high TIBC, and low MCV. What could be the possible diagnosis?",
        "options": [
          "Megaloblastic anemia",
          "Iron deficiency anemia",
          "Sideroblastic anemia",
          "Anemia of chronic disease"
        ],
        "answer": "Iron deficiency anemia"
      },
      {
        "question": "An adult patient presents with fatigue and pallor. Routine blood investigations show low RBC count, low Hb, MCV = 60 fL, MCH = 20 pg. Diagnosis is:",
        "options": [
          "Plasma cell leukemia",
          "AML",
          "ACD",
          "IDA"
        ],
        "answer": "IDA"
      },
      {
        "question": "A 70-year-old male with hip pain and lytic lesions in the hip bone. Serum calcium levels were raised. Given the image represents:",
        "options": [
          "Hyperparathyroidism",
          "Multiple myeloma",
          "ALL",
          "Hypercalcemia"
        ],
        "answer": "Multiple myeloma"
      },
      {
        "question": "An elderly patient presents with complaints of fatigue, lower back pain, and headache for the last few weeks. Lab investigations revealed elevated ESR and X-ray showed multiple punched-out lesions in the skull. Which of the following is the best investigation for this patient?",
        "options": [
          "Serum electrophoresis showing IgG",
          "Serum levels of CA15-3",
          "Whole body PET scan",
          "CT head with contrast"
        ],
        "answer": "Whole body PET scan"
      },
      {
        "question": "Which of the following interferes with iron absorption?",
        "options": [
          "Vitamin C",
          "Phytates",
          "Oxalate",
          "Myoglobin"
        ],
        "answer": "Phytates"
      },
      {
        "question": "Correct about Anemia of chronic disease?",
        "options": [
          "High ferritin",
          "High transferrin",
          "Increased percentage of saturation of transferrin",
          "High serum iron"
        ],
        "answer": "High ferritin"
      },
      {
        "question": "Which type of anemia is seen in patients with rheumatoid arthritis?",
        "options": [
          "Normocytic and hypochromic anemia",
          "Microcytic and hypochromic anemia",
          "Normocytic and normochromic anemia",
          "Macrocytic anemia"
        ],
        "answer": "Normocytic and normochromic anemia"
      },
      {
        "question": "Which of the following is the correct sequence of early erythropoiesis in a developing fetus?",
        "options": [
          "Yolk sac, bone marrow, and liver",
          "Yolk sac, liver, and bone marrow",
          "Liver, bone marrow, and yolk sac",
          "Bone marrow, yolk sac, and liver"
        ],
        "answer": "Yolk sac, liver, and bone marrow"
      },
      {
        "question": "WHO cut-off for diagnosis of anemia in nonpregnant females?",
        "options": [
          "7 g%",
          "10 g%",
          "11 g%",
          "12 g%"
        ],
        "answer": "12 g%"
      },
      {
        "question": "Which of the following tests is to be done to screen a lady with a family history of thalassemia?",
        "options": [
          "Elevated HbA2",
          "NESTROFT",
          "High-performance liquid chromatography",
          "DNA"
        ],
        "answer": "Elevated HbA2"
      },
      {
        "question": "Which of the following is best to confirm the diagnosis of thalassemia trait in a lady with a positive family history?",
        "options": [
          "HbA2 Levels",
          "Reticulocytosis",
          "Peripheral Smear",
          "Hemoglobin electrophoresis"
        ],
        "answer": "Hemoglobin electrophoresis"
      },
      {
        "question": "Heinz bodies are composed of:",
        "options": [
          "RNA",
          "Denatured hemoglobin",
          "Bacterial RNA",
          "Mitochondrial proteins"
        ],
        "answer": "Denatured hemoglobin"
      },
      {
        "question": "Positive Coombs test is seen in which hemolytic anemia?",
        "options": [
          "Sickle cell anemia",
          "Autoimmune hemolytic anemia",
          "Hereditary spherocytosis",
          "G6PD deficiency"
        ],
        "answer": "Autoimmune hemolytic anemia"
      },
      {
        "question": "Arsenic is used in the treatment of?",
        "options": [
          "AML",
          "TTP",
          "Myeloproliferative disease",
          "ALL"
        ],
        "answer": "AML"
      },
      {
        "question": "Which virus leads to Aplastic Crisis?",
        "options": [
          "Pox virus",
          "Parvovirus B19",
          "Hepatitis A",
          "Epstein-Barr virus"
        ],
        "answer": "Parvovirus B19"
      },
      {
        "question": "Which of the following will lead to X-ray appearance of \"crew cut appearance\" with Gamma-Gandy bodies?",
        "options": [
          "Amyloidosis",
          "Acute myeloid leukemia",
          "Osteoporosis",
          "ALL"
        ],
        "answer": "Osteoporosis"
      },
      {
        "question": "Rosenthal syndrome occurs due to deficiency of:",
        "options": [
          "Mixed cellularity",
          "Nodular sclerosis",
          "Hereditary spherocytosis",
          "Thalassemia"
        ],
        "answer": "Nodular sclerosis"
      },
      {
        "question": "JAK-2 mutation is seen in:",
        "options": [
          "Polycythemia vera",
          "CML",
          "AML",
          "Essential thrombocythemia"
        ],
        "answer": "Polycythemia vera"
      },
      {
        "question": "Which of the following is a B-cell disease?",
        "options": [
          "Thalassemia",
          "CML",
          "Hodgkin lymphoma",
          "Acute lymphocytic leukemia"
        ],
        "answer": "Hodgkin lymphoma"
      },
      {
        "question": "Lacunar Reed-Sternberg cell is found in which type of Hodgkin's lymphoma?",
        "options": [
          "Mixed cellularity",
          "Lymphocyte rich",
          "Lymphocyte depleted",
          "Nodular sclerosis"
        ],
        "answer": "Nodular sclerosis"
      },
      {
        "question": "The cause of severe hemorrhage in acute promyelocytic leukemia is?",
        "options": [
          "Disseminated intravascular coagulation",
          "Immune complex deposits on blood vessels",
          "Thrombocytopenia",
          "Coagulopathy"
        ],
        "answer": "Disseminated intravascular coagulation"
      },
      {
        "question": "Which is the most common Hodgkin's lymphoma?",
        "options": [
          "Lymphocyte rich",
          "Lymphocyte depleted",
          "Nodular sclerosis",
          "Mixed cellularity"
        ],
        "answer": "Mixed cellularity"
      },
      {
        "question": "Prevalence of Burkitt's lymphoma is highest in:",
        "options": [
          "Australia",
          "Africa",
          "America",
          "Asia"
        ],
        "answer": "Africa"
      },
      {
        "question": "Reticulocytosis is NOT seen in:",
        "options": [
          "Sickle cell anemia",
          "Thalassemia",
          "Lead poisoning",
          "Iron deficiency anemia"
        ],
        "answer": "Lead poisoning"
      },
      {
        "question": "Splenectomy is useful in which of the following?",
        "options": [
          "Sickle cell anemia",
          "Good pasture syndrome",
          "Hereditary spherocytosis",
          "Thalassemia"
        ],
        "answer": "Hereditary spherocytosis"
      },
      {
        "question": "Child with anemia having MCV 76 fL. He is not responding to any medication and has a history of getting repeated blood transfusions. Which of the following is the next line of investigation?",
        "options": [
          "Hemoglobin electrophoresis",
          "Osmotic fragility test",
          "Serum ferritin levels",
          "Folate levels"
        ],
        "answer": "Hemoglobin electrophoresis"
      },
      {
        "question": "Child with anemia having MCV 80-100 fL and is not responding to any medication. Which of the following is the next line of investigation?",
        "options": [
          "Osmotic fragility test",
          "Hemoglobin electrophoresis",
          "Serum ferritin levels",
          "Coombs test"
        ],
        "answer": "Hemoglobin electrophoresis"
      },
      {
        "question": "A 10-year-old boy presented with a swollen knee after suffering trauma. Which of the following is the likely condition seen in this patient?",
        "options": [
          "Von Willebrand disease",
          "Factor 8 deficiency",
          "Immune thrombocytopenia",
          "Vitamin K deficiency"
        ],
        "answer": "Factor 8 deficiency"
      },
      {
        "question": "A 3-year-old child is having progressive anemia. On examination, splenomegaly is noted with malar eminence prominence. Peripheral smear is shown here. The clinical diagnosis is:",
        "options": [
          "Thalassemia",
          "Sideroblastic anemia",
          "Iron deficiency anemia",
          "Lead poisoning"
        ],
        "answer": "Thalassemia"
      },
      {
        "question": "Owl eye appearance of cells in urine microscopic examination of post kidney transplant patient is a feature of:",
        "options": [
          "CMV",
          "HL",
          "AML",
          "CLL"
        ],
        "answer": "CMV"
      },
      {
        "question": "A 4-year-old child presents with fever, petechial spots, fatigue, pallor, hepatosplenomegaly, and sternal tenderness. The clinical situation described above is most consistently associated with which of the following?",
        "options": [
          "Multiple myeloma",
          "EBV",
          "NH",
          "Tuberculosis"
        ],
        "answer": "EBV"
      },
      {
        "question": "Extrinsic pathway of clotting factors is measured by:",
        "options": [
          "Prothrombin time",
          "Activated partial thromboplastin time",
          "Bleeding time",
          "Clotting time"
        ],
        "answer": "Prothrombin time"
      },
      {
        "question": "G6PD helps in maintaining the integrity of RBC by:",
        "options": [
          "Controlling oxidative stress on RBC",
          "Controlling reduction stress on RBC",
          "Maintaining flexibility of cell membrane",
          "Component of electron transport chain"
        ],
        "answer": "Controlling oxidative stress on RBC"
      },
      {
        "question": "Low TIBC is seen in:",
        "options": [
          "Anemia of chronic disease",
          "Iron deficiency anemia",
          "Fanconi anemia",
          "Aplastic anemia"
        ],
        "answer": "Anemia of chronic disease"
      },
      {
        "question": "Comment on type of anemia in peripheral smear:",
        "options": [
          "Iron deficiency anemia",
          "Hereditary spherocytosis",
          "Sickle cell anemia",
          "Pernicious anemia"
        ],
        "answer": "Iron deficiency anemia"
      },
      {
        "question": "Fetal hemoglobin has which of these features?",
        "options": [
          "Most susceptible to denaturation by acid",
          "Resistant to denaturation by alkali",
          "By 20 weeks, 90% of fetal Hb is HbF",
          "It has 2 alpha and 2 beta chains"
        ],
        "answer": "By 20 weeks, 90% of fetal Hb is HbF"
      },
      {
        "question": "Which is the lifespan of transfused RBC?",
        "options": [
          "30 days",
          "60 days",
          "45 days",
          "120 days"
        ],
        "answer": "45 days"
      },
      {
        "question": "Schistocytes are seen in:",
        "options": [
          "HUS",
          "Abetalipoproteinemia",
          "Anemia of chronic disease",
          "Sideroblastic anemia"
        ],
        "answer": "HUS"
      },
      {
        "question": "All are seen in thalassemia major, EXCEPT:",
        "options": [
          "Transfusion dependency",
          "Splenohepatomegaly",
          "Ineffective erythropoiesis",
          "Macrocytic anemia"
        ],
        "answer": "Macrocytic anemia"
      },
      {
        "question": "Low iron and low TIBC is seen in:",
        "options": [
          "Aplastic anemia",
          "Nodular sclerosis",
          "Mixed cellularity",
          "Lymphocyte predominant"
        ],
        "answer": "Aplastic anemia"
      },
      {
        "question": "Which is the most common type of Hodgkin's lymphoma?",
        "options": [
          "Mixed cellularity",
          "Lymphocyte predominant",
          "Nodular sclerosis",
          "Lymphocyte depleted"
        ],
        "answer": "Mixed cellularity"
      },
      {
        "question": "Which is the most common ALL subtype?",
        "options": [
          "Pre B cell",
          "Pre T cell",
          "B cell",
          "T cell"
        ],
        "answer": "B cell"
      },
      {
        "question": "All cause Reticulocytosis; EXCEPT:",
        "options": [
          "Aplastic anemia",
          "Sickle cell anemia",
          "EBV",
          "Myelofibrosis"
        ],
        "answer": "Aplastic anemia"
      },
      {
        "question": "Hodgkin's lymphoma is caused by:",
        "options": [
          "EBV",
          "CMV",
          "HHV8",
          "HHV6"
        ],
        "answer": "EBV"
      },
      {
        "question": "Which is the most common defectively produced antibody in multiple myeloma?",
        "options": [
          "IgG",
          "IgA",
          "IgM",
          "IgD"
        ],
        "answer": "IgA"
      }
    ]
  }
};
